### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by quant42** [eeg-ebe/HaplowebMaker#22] opened 2017-12-16 22:46 UTC
Well some of the code was written in a bit of haste and is not as universal/clear as it should be.

Clean it up!

**Comment by jflot** [comment] 2018-03-26 10:33
We need to make the calculation faster (notably when no haploweb is needed, only the conspecificity matrix).

**Comment by jflot** [comment] 2020-07-19 13:32
Still on the todo-list.

**Comment by jflot** [comment] 2020-07-19 13:44
Actually a duplicate of #37, hence I close it.

**Closed as completed by jflot** 2020-07-19 13:44 UTC
Labels: enhancement, urgent
